### ISSUE TITLE
Avoid duplicating type tests

### ISSUE THREAD

**Issue by rluvaton** [rluvaton/expect-http-client-matchers#23]
Currently, we clone all type tests across 5 files, it would be helpful to generate those out of the same file

**Comment by Tamir-M** [comment]
Do you mean something like this:

```mjs
// types-test/generate.mjs
import fs from "fs";
import path from "path";

const generatedTest = `
import axios from 'axios';

async function run() {
    const res = await axios.get('http://example.com');

    expect(res).toBeTruthy();

    expect(res).toBeSuccessful();
    expect(res).not.toBeSuccessful();
    ${// rest of our matchers}
}

run();
`
fs.writeFileSync(path.join(ROOT_DIR, 'types-test', 'expect-type-tests', 'types.test.ts'), generatedTest);
fs.writeFileSync(path.join(ROOT_DIR, 'types-test', 'jest-all-type-tests', 'types.test.ts'), generatedTest);
// rest of the types-test folders
```

Ofc there would still be a reason to run the tests to verify it's all working correctly, but this way you only need to write it once to apply changes to all 5 places.

**Comment by rluvaton** [comment]
sort of, I would still have each file but would have some kind of template that we will insert to - handlebar style

**Comment by Tamir-M** [comment]
Yeah all files will still be tracked by git, this is just an easier way to write to those files so we don't have to write the same thing 5 times each time we add a matcher.
I will work on this tomorrow.

**Comment by rluvaton** [comment]
For now it seems ok
